elao_enum:
    # Provide the enum classes for which you want to automatically generate & register Doctrine DBAL Types:
    # https://github.com/Elao/PhpEnums#doctrine
    doctrine:
        types:
            Status: App\Model\Enum\Status
            ApplicationStatus: App\Model\Enum\ApplicationStatus
            Gender: App\Model\Enum\Gender
            Source: App\Model\Enum\Source
            Reason: App\Model\Enum\Reason
            Type: App\Model\Enum\Type
