nelmio_cors:
    defaults:
        allow_origin: []
        allow_methods: []
        allow_headers: []
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['http://localhost:3000', 'http://localhost']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            max_age: 3600
        '^/auth/':
            allow_origin: ['http://localhost:3000', 'http://localhost']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            max_age: 3600
