version: '3.8'

services:
  web:
    image: nginx:1.19.2-alpine
    container_name: crm-web
    volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
        - ./:/var/www/app
    restart: unless-stopped
    depends_on:
        - app
        - db
    ports:
        - 80:80
  db:
    container_name: ${DB_HOST}
    image: postgres:12.4-alpine
    restart: unless-stopped
    environment:
          - POSTGRES_DB=${DB_NAME}
          - POSTGRES_USER=${DB_USER}
          - POSTGRES_PASSWORD=${DB_PASS}
    ports:
        - 5432:5432
    volumes:
        - db-data:/var/lib/postgresql/data/
  app:
    build: ./
    container_name: crm-api
    restart: unless-stopped
    volumes:
        - ./:/var/www/app
volumes:
    db-data: